
version: 2

models:
  - name: stg_film_permits
    description: '{{ doc("stg_film_permits") }}'
    config:
      materialized: table
    meta:
      contains_pii: false
      owner: "@giacomo"
    tags:
      - film
      - mome
      - movie
      - permit
      - silver
    columns:
      - name: borough
        description: First borough of activity for the day
        data_tests:
          - not_null
      - name: category
        description: Description of production as selected by permit applicant
        data_tests:
          - not_null
          - accepted_values:
              values:
                - Commercial
                - Documentary
                - Film
                - Music Video
                - Still Photography
                - Student
                - Television
                - Theater
                - WEB
      - name: country
        description: Project origin
      - name: end_datetime
        description: Activity scheduled to be completed
        data_tests:
          - not_null
      - name: entered_on
        description: Date permit request submitted to MOME
        data_tests:
          - not_null
      - name: event_agency
        data_tests:
          - not_null
      - name: event_id
        description: Auto-generated unique event identification number.
        data_tests:
          - not_null
          - unique
      - name: event_type
        description: '{{ doc("film_permits_event_type") }}'
        data_tests:
          - not_null
          - accepted_values:
              values:
                - DCAS Prep/Shoot/Wrap Permit
                - Rigging Permit
                - Shooting Permit
                - Theater Load in and Load Outs
      - name: start_datetime
        description: Activity scheduled to begin
      - name: zipcode
        description: First zip code of production activity
        data_tests:
          - not_null

  - name: stg_service_requests_311
    description: '{{ doc("stg_service_requests_311") }}'
    config:
      materialized: table
    meta:
      contains_pii: false
      owner: "@giacomo"
    tags:
      - '311'
      - complaint
      - nyc
      - silver
    columns:
      - name: agency
        description: >
          The NYC agency that received a complaint from a New Yorker.
        data_tests:
          - not_null
          # - accepted_values: # There are 33 different agencies, I'm not going to list them all
          #     values:
          #       - ACS
          #       - DOT
          #       - NYPD
      - name: borough
        description: One of the borough in NYC.
        data_tests:
          - accepted_values:
              values:
                - BRONX
                - BROOKLYN
                - MANHATTAN
                - QUEENS
                - STATEN ISLAND
                - Unspecified
      - name: complaint_type # There is some crazy stuff in here. Need a good dose of data cleaning
        data_tests:
          - not_null
      - name: created_date
        data_tests:
          - not_null
      - name: unique_key
        description: Unique identifier for a 311 service request.
        data_tests:
          - not_null
          - unique
