version: 2

sources:
  - name: nyc_open_data
    description: >
      Various datasets found on the [NYC Open Data portal](https://opendata.cityofnewyork.us/).
    database: nyc_open_data # DuckDB catalog
    schema: landing_zone # DuckDB schema
    meta:
      contains_pii: false
      loader: dlt
      owner: "@giacomo"
    tags:
      - bronze
      - nyc
      - raw
      - source
    tables:
      - name: film_permits
        description: '{{ doc("src_film_permits") }}'
        identifier: film_permits
        loader: dlt
        loaded_at_field: ingested_at
        columns:
          - name: eventid
            description: The unique ID of a film permit.
        tags:
          - film
          - mome
          - movie
          - permit

      - name: service_requests_311
        description: '{{ doc("src_service_requests_311") }}'
        freshness:
          warn_after:
            count: 24
            period: hour
          error_after:
            count: 30
            period: day
        identifier: service_requests_311
        loader: dlt
        loaded_at_field: ingested_at
        columns:
          - name: unique_key
            description: The primary key for this table.
            data_tests:
              - not_null
              - unique
        tags:
          - '311'
          - complaint

      - name: staten_island_ferry_ridership_counts
        description: >
          NYC Open Data dataset [Staten Island Ferry Ridership Counts](https://data.cityofnewyork.us/Transportation/Staten-Island-Ferry-Ridership-Counts/6eng-46dm/about_data).
        identifier: staten_island_ferry_ridership_counts
        loader: dlt
        loaded_at_field: ingested_at
        columns:
          - name: date
        tags:
          - ferry
