name: 'NYC_Open_Data'
profile: 'nyc_open_data' # profiles.yml in this directory, or ~/.dbt/profiles.yml
version: '1.0.0'

analysis-paths: ["analyses"]
macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_open_data: # This should match the `name` above
    staging:
      materialized: table
